=== VWenX/zoeey/src/main/resources/DispatchConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://xml.zoeey.org/schema/DispatchConfig"
    xmlns:tns="http://xml.zoeey.org/schema/DispatchConfig"
    elementFormDefault="qualified">
    <xsd:element name="root">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="init">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="ignoreCase" type="xsd:boolean" fixed="true"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="entrys">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="entry" type="tns:entry" minOccurs="0" maxOccurs="unbounded"/>
                            <xsd:element name="annots" minOccurs="0" maxOccurs="1">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="annot" type="tns:annot" maxOccurs="unbounded"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="entry">
        <xsd:sequence>
            <xsd:element name="pattern" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="publish" type="javaee:fully-qualified-classType"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="annot"></xsd:complexType>
</xsd:schema>

=== VWenX/zoeey/src/test/resources/DispatchConfig.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : RouterConfig.xml
    Created on : 2009年8月6日, 上午11:13
    Author     : MoXie
    Description:
        Purpose of the document follows.
-->

<zo:root  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
          xmlns:zo='http://xml.zoeey.org/schema/DispatchConfig'
          xsi:schemaLocation='http://xml.zoeey.org/schema/DispatchConfig DispatchConfig.xsd'>
    <zo:init>
        <zo:ignoreCase>true</zo:ignoreCase>
    </zo:init>
    <zo:entrys>
        <zo:annots>
            <zo:annot>org.zoeey.dispatch.ArticlePublish</zo:annot>
            <zo:annot>org.zoeey.dispatch.ArticlePublish</zo:annot>
        </zo:annots>
        <!--
            publish
        -->
        <zo:entry>
            <zo:pattern>/loaderExample</zo:pattern>
            <zo:pattern>/loader</zo:pattern>
            <zo:publish>org.zoeey.dispatch.ArticlePublish</zo:publish>
        </zo:entry>
        <zo:entry>
            <zo:pattern>/validator</zo:pattern>
            <zo:publish>org.zoeey.dispatch.ArticlePublish</zo:publish>
        </zo:entry>
        <zo:entry>
            <zo:pattern>/fireJava</zo:pattern>
            <zo:publish>org.zoeey.dispatch.ArticlePublish</zo:publish>
        </zo:entry>
        <!--
            init
        -->
        <zo:entry>
            <zo:publish>org.zoeey.dispatch.TimePublish</zo:publish>
        </zo:entry>

        <zo:entry>
            <zo:publish>org.zoeey.dispatch.TimePublish</zo:publish>
        </zo:entry>
    </zo:entrys>
</zo:root>
